smartprocure/contexture-elasticsearch

CHANGELOG.md
package.json
src/example-types/default.js
src/example-types/results.js
test/example-types/results.js
test/types.js

Fix the`extendAll` bug and adding a verbose config test

Fixing the extendAll bug and adding a unit test for "verbose" config

---

CHANGELOG.md
package.json
src/index.js

Our use of extendAll was wrong, it expects an array.

Fixing extendAll

---

CHANGELOG.md
package.json
src/index.js

Keeping it as it is would make the config.request headers go instead of the requestorContext if they were present.

Passing the headers properly with requestorContext

---

CHANGELOG.md
package.json
src/example-types/results.js
test/example-types/results.js
test/types.js

The `results` type will now support `includes` and `excludes` to better filter the data that's received.

v0.1.2, results with includes and excludes

---

CHANGELOG.md
package.json
src/index.js

Utility function to get a mapping used for building a schema directly from ES

Mapping util

---

CHANGELOG.md
package.json
src/example-types/number.js

Number type no longer wraps results in a results property.

Number type no longer wraps results in a results property.

---

CHANGELOG.md
package.json
src/example-types/facet.js

:) empty string or undefined was never a valid option anyway

Default size back to 10

---

CHANGELOG.md
README.md
package.json
src/example-types/results.js
test/example-types/results.js

forceExclude on the results type allows us to extend any existing exclude value (even if empty) with a default list of forceExclude fields defined at the schema.

Forcing Exclusions

---

.circleci/config.yml
CHANGELOG.md
package.json
src/example-types/numberUtil.js
test/example-types/number.js

Number types will now return extended instead of standard stats.

Number types will now return extended instead of standard stats.

---

CHANGELOG.md
README.md
package.json
src/example-types/__all.js
src/example-types/schemaMapping.js
src/index.js
src/schema.js
test/schema-data/imdb-aliases.js
test/schema-data/imdb-mapping.js
test/schema-data/imdb-schema.js
test/schema.js
test/types.js

Closes #86
* Format CHANGELOG
* Added `getSchemas`, a utility that reads from es mappings/aliases to automatically generate schemas (complete with field definitions as well)
* Added `exampleTypeSchemaMapping` to map es types to example contexture node types

Dynamic schemas

---

CHANGELOG.md
package.json
src/example-types/schemaMapping.js

* Avoid object spread in mapping util to make browser usage easier

Avoid object spread in mapping util to make browser usage easier

---

CHANGELOG.md
package.json
src/schema.js
test/schema-data/imdb-mapping.js

Apparently mappings can sometimes be empty, so omit them to be safe

Handle empty mappings

---

CHANGELOG.md
package.json
src/schema.js

When ES index name starts with a period, the F method invertByArray creates a field which has a value 
which is not an array and the deconstruct in the following _.mapValues fails. Here is an example of what invertByArray produces when an index name starts with a period:
```
{ '': { kibana: [ '.kibana_1' ] },
'bid-data': [ 'bid-2018.10.31' ],
'bid-data-beta': [ 'bid-2018.10.31' ],
'include-in-snapshot': [ 'bid-2018.10.31', 'bid-2018.12.20', 'bid-2018.12.28b' ],
'cage-data': [ 'cage-20170507-es6' ],
'fpds-current': [ 'fpds-20180811-es6' ],
'fpds-documents': [ 'fpds-20180811-es6' ],
fpds_current: [ 'fpds-20180811-es6' ],
'gov-contacts': [ 'gov-contacts-2018.06.21c-es6-2' ],
'gsa-data-import': [ 'gsa-20171228-es6-2' ],
'nsn-data': [ 'nsn-20170507-es6-2' ],
'smartcontacts-data-import': [ …
```

Fix index name beginning with period breaks schema to alias mappings

---

CHANGELOG.md
package.json
src/example-types/facet.js
src/example-types/results.js
src/example-types/schemaMapping.js
src/fields.js
src/index.js
test/example-types/facet.js
test/schema-data/imdb-schema.js

* Globally check for `notAnalyzedField` from field util instead of just results
* Fix scan/scroll on latest core (don't check `config`)
* Support `scroll: true` which now defaults to 2m instead of exploding
* Support tagsText in typeOptions for text fields
* Facet: Add explicit size:0 support (which sets it to es's max integer size of `2^31 - 1`)

Subquery prep

---

CHANGELOG.md
package.json
src/example-types/results.js
test/example-types/results.js

Fixes #117 
* restricts highlighting to context.includes unless context.showOtherMatches is set truthy

feature/117 - restrict ES highlighting to included fields unless context.showOtherMatches

---

CHANGELOG.md
package.json
src/example-types/results.js
src/highlighting.js
test/example-types/results.js
test/highlighting.js

inlineAliases allow for mapping of a field in the `hit._source` with the value of a field in ES response `highlight` object.

Add the inlineAliases highlighting support

---

CHANGELOG.md
package.json
src/index.js
test/example-types/geo.js

Since we are in ES specific context make sure the error is streamlined and not the monolithic object that comes from ES by default. We mainly need the error message and the specific type it is.

Throw message & error obj on client run exception

---

CHANGELOG.md
package.json
src/example-types/results.js
test/example-types/results.js

- Allow for search override of the highlight section so it is not always global but per search tree if needed
- Adjust the tests so that `include` is always an array for consistency

Latest highlighting changes

---

CHANGELOG.md
package.json
src/example-types/results.js

- Makes sure that the `inlineAliases` are actually part of the final filtered fields on witch to actually highlight on. The issue was that `inlineAliases` ware filtered out.

Include variations fix

---

CHANGELOG.md
package.json
src/example-types/esTwoLevelAggregation.js
test/example-types/matchCardinality.js

esTwoLevelAgg filters its buckets for metrics with falsy values (currently including zeros), and if it finds one it strips off a bunch of information from the result. I don't really understand this behavior, but I assume it's fine - we just don't want it to happen for zeros.
Since the twoLevelAgg type doesn't have any test cases of its own, I took advantage of the matchCardinality test case to illustrate zero/null handling. (Admittedly a weird choice, but It also shows that it happens with _any_ property with `{ value: null }` in a twoLevelAgg bucket, even cardinality.)

Fix zero value handling in esTwoLevelAggregation

---

CHANGELOG.md
package.json
src/example-types/dateRangeFacet.js
src/example-types/geo.js
src/example-types/results.js
src/example-types/smartIntervalHistogram.js
src/index.js
src/schema.js
test/example-types/results.js
test/example-types/testUtils.js

Fixes #128 
* BREAKING: Assumes the elasticsearch client is the new @elastic/elasticsearch npm package. Will not work with the old `elasticsearch` package
* BREAKING: Removed unused `getMappingProperties` API
* Errors are now gracefully caught on a per node basis and properly set on node.error. This means that a node can throw an error, but the rest of the search will continue properly and also not log an uncaught exception to the console. This means the contexture dev tools can now be used to see raw ES errors.
* Simplifed runSearch with modern JS syntax
* Get mappings now handles type-less mappings, which is the default on ES7+ (while still handling types for ES6-)
* [DateRangeFacet] converted to `dateOptionalTime` format which works on ES 6 and 7
* [Results] track_total_hits and handle …

Elasticsearch 7 (and new elastic client) support

---

CHANGELOG.md
package.json
src/example-types/filters/tagsQuery.js
test/example-types/filters/tagsQuery.js

FIxes #162 
* runs search for each tag and returns counts suitable with which to mark up the tags

feature/162 - add tag counts to tagsQuery

---

CHANGELOG.md
package.json
src/index.js

This was something that was intended to be refactored as part of v1 but was never
completed. This change brings back the previous behavior until the refactor is
able to be completed.

Fix bug, contexture error response being omitted from thrown error.

---

CHANGELOG.md
package.json
src/index.js

This is a quick fix solution to an issue where the count associated with results will be different than the number of results that are scrolled through. The root cause of the issue has to do with deep-pagination and the size of the value assigned to`scroll` (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#scroll-search-results)).
After this, we should start transitioning away from `scrollid` and start making use of `search_after` and point in time `pit`. But that requires more research around the use of the mechanism for smaller paginations and (less than 10,000) vs larger ones.

Increased the scroll value

---

CHANGELOG.md
package.json
src/example-types/metricGroups/dateIntervalGroupStats.js
src/example-types/metricGroups/fieldValuePartitionGroupStats.js
src/example-types/metricGroups/fieldValuesGroupStats.js
src/example-types/metricGroups/numberIntervalGroupStats.js
src/example-types/metricGroups/numberRangesGroupStats.js
src/example-types/metricGroups/percentilesGroupStats.js
test/example-types/metricGroups/fieldValuePartitionGroupStats.js
test/example-types/metricGroups/fieldValuesGroupStats.js

- Example types' context is now valid even if `statsField` is not passed.
- Use `getField` in `fieldValuePartitionGroupStats` to map field to its un-analyzed value.

Small example types fixes

---

CHANGELOG.md
package-lock.json
package.json
src/index.js
test/index.js

This will allow us to pass headers and things like requestTimeout on a per search basis.

feat: create a child client on every search

---

CHANGELOG.md
package.json
src/example-types/filters/date.js
src/example-types/filters/dateRangeFacet.js
test/example-types/filters/date.js
test/example-types/filters/dateRangeFacet.js
test/example-types/metricGroups/fieldValuesDelta.js

- Moves away from the deprecated `dateOptionalTime` and replaces it with the recommended `date_optional_time`

Move to `date_optional_time`

---

CHANGELOG.md
package-lock.json
package.json
src/example-types/metricGroups/pivot.js

Fix bug with pivot processReponse including groups that weren't in the query when setting a drilldown

Fix: Pivot drilldown nested cases

---

CHANGELOG.md
package-lock.json
package.json
src/schema.js
test/schema-data/schema-with-types.js
test/schema-data/schema-without-types.js

* Add `aliasOf` to elastic schemas (for better alias handling)
Today, aliases just show up as regular schemas. That's helpful, but it's sometimes helpful to know if you're dealing with an alias or not (for example, to filter to just one alias for a given index based on some arbitrary rules in a schema picker).

Schema alias improvements

---

CHANGELOG.md
package.json
src/example-types/metricGroups/pivot.js
test/example-types/metricGroups/pivot.js
test/example-types/metricGroups/pivotData/columnResult.js
test/example-types/metricGroups/pivotData/pivotRepsonseWithFilteredFieldValueGroup.js
test/example-types/metricGroups/pivotData/pivotResponse.js

Pivot: fix for root level aggregations

---

CHANGELOG.md
package.json
src/example-types/metricGroups/pivot.js
test/example-types/metricGroups/pivot.js

Fix: pivot total column count sort

---

CHANGELOG.md
package.json
src/example-types/metricGroups/pivot.js
test/example-types/metricGroups/pivot.js

Pivot node: deprecating subtotals

---

CHANGELOG.md
package-lock.json
package.json
src/example-types/metricGroups/pivot.js
test/example-types/metricGroups/pivot.js
test/example-types/metricGroups/pivotData/columnResponse.js
test/example-types/metricGroups/pivotData/columnResult.js
test/example-types/metricGroups/pivotData/pivotRepsonseWithFilteredFieldValueGroup.js
test/example-types/metricGroups/pivotData/pivotResponse.js

Refactor pivot node: renaming groups to rows

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/example-types/filters/tagsQuery.js
src/example-types/index.js
src/example-types/metricGroups/tagsQueryGroupStats.js
test/example-types/filters/tagsQuery.js
test/example-types/metricGroups/pivot.js
test/example-types/metricGroups/tagsQueryGroupStats.js
test/types.js

- Create `tagsQueryGroupStats` type for use with pivot filters
- Allow additional parameters for `buildGroupQuery` on the `tagsQuery` filter type
- Add tests for both cases

feat: create tagsQueryGroupStats type

---

CHANGELOG.md
package-lock.json
package.json
src/example-types/metricGroups/fieldValuesGroupStats.js
src/example-types/metricGroups/pivot.js
test/example-types/metricGroups/pivot.js

- Create filter for every field in `additionalFields` in fieldValuesGroupStats
- Modify pivot node to handle single node returning an array of drilldown filters
- Add testing

Support drilldowns with additional fields (multi-term aggregation) for `fieldValuesGroupStats` type

---

CHANGELOG.md
package.json
src/schema.js

This will prevent the app from starting all together, this is simple to fix but somewhat difficult to identify, this simply makes it more obvious which index is having issue being processed.

Throw a more informative error when processing mappings
