smartprocure/contexture-elasticsearch

CHANGELOG.md, package.json, src/index.js
=> Using extend instead of the three dots syntax

CHANGELOG.md, package.json, src/example-types/terms_stats.js, src/index.js, test/example-types/text.js
swap request config override order
=> swap request config override order

CHANGELOG.md, package.json, src/example-types/text.js, test/example-types/text.js
See #13 for more information.
Fixes #13
Please review! 🙏
=> Using regexp instead of wildcard in the text type

CHANGELOG.md, package.json, src/example-types/percentilesRange.js, src/example-types/text.js, test/example-types/percentileRange.js, test/example-types/text.js
Fixes the percentile range to now show more accurate % ranges
=> PercentileRange fixes

.gitignore, CHANGELOG.md, README.md, package.json, src/types.js, test/example-types/testUtils.js
Using directory-metagen instead of include-all
=> Using directory-metagen instead of include-all

src/example-types/number.js, test/example-types/number.js
=> number type without context.data and context.config

src/example-types/nonzeroClusters.js, test/example-types/nonzeroClusters.js
=> nonzeroClusters type without context.data and context.config

CHANGELOG.md, package.json, src/example-types/facet.js
=> Removed the last reference to context.data from facet

CHANGELOG.md, package.json, src/example-types/number.js
=> Check for is number instead of value.

CHANGELOG.md, package.json, src/example-types/facet.js
=> Facet wasn't allowing size 0

CHANGELOG.md, README.md, package.json, src/example-types/date.js, src/example-types/geo.js, test/example-types/date.js
Here I’m adding a way to step out of the date formatting.
=> useRaw to step out from the date formatting

CHANGELOG.md, README.md, package.json, src/example-types/__all.js, src/example-types/geo.js, src/example-types/number.js, src/example-types/numberRangeHistogram.js, src/example-types/numberUtil.js, test/example-types/number.js, test/types.js
* Introducing new example type number range histogram.
* Number now supports find the best functionality.
* Geo type now guards against 0 results in geocoder.
=> Changes to number types.

CHANGELOG.md, package.json, src/example-types/facet.js
=> Full cardinality for facet searches with includeZeroes

CHANGELOG.md, package.json, src/example-types/results.js
=> include triggers verbose

src/example-types/smartIntervalHistogram.js
Not sure how it ended up there.
=> Fixed a silly or

CHANGELOG.md, package.json, src/example-types/nLevelAggregation.js, src/example-types/terms_stats.js
Use field mode for terms stats.
=> Use field mode for terms stats.

CHANGELOG.md, package.json, src/example-types/results.js, src/highlighting.js
... should include fields missing from the include array.
Version 0.11.0
=> Additional highlighted fields

CHANGELOG.md, package.json, test/highlighting.js
I forgot to add these in my previous PR!
=> highlighting tests

CHANGELOG.md, package.json, src/example-types/nLevelAggregation.js, src/example-types/schemaMapping.js, src/regex.js
* Add geo_point type default on example type mapping
=> Add geo_point type default on example type mapping

CHANGELOG.md, package.json, src/example-types/schemaMapping.js, test/schema-data/imdb-schema.js
* Use tagsQuery instead of facet if there is no nested notAnalyzedField
=> No facet without keyword field

CHANGELOG.md, README.md, package.json, src/example-types/cardinality.js, test/example-types/cardinality.js
Added support for fieldMode on the cardinality type.
=> fieldMode support on cardinality

CHANGELOG.md, package.json, src/example-types/schemaMapping.js, test/schema-data/imdb-schema.js
* Adds mapping for boolean and integer ES types
* Adds exists as a type option for all fields
=> Boolean & Integer Handling (and Exists Type Default)

CHANGELOG.md, package.json, src/example-types/tagsQuery.js, test/example-types/tagsQuery.js
=> auto isPhrase if isPhrase not set

CHANGELOG.md, package.json, src/index.js
* Fix scroll for subsequent scroll requests
=> Fix scroll for subsequent scroll requests

CHANGELOG.md, package.json, src/example-types/tagsText.js
=> Fix typo on `tagsText` example type

CHANGELOG.md, README.md, package.json, src/aggUtils.js, src/example-types/esTwoLevelAggregation.js, src/example-types/terms_stats.js, test/example-types/dateHistogram.js, test/example-types/matchCardinality.js, test/example-types/matchStats.js, test/example-types/rangeStats.js, test/example-types/terms_stats.js, test/example-types/twoLevelMatch.js
=> implement include support for terms_stats

CHANGELOG.md, package.json, src/example-types/nLevelAggregation.js, src/example-types/numberUtil.js, src/example-types/results.js, src/highlighting.js, src/schema.js, test/highlighting.js, test/schema.js
- Support to provide configuration per field for highlighting
- Support to provide `.*` highlighting for fields (in the case of `documents.*`)
- Added tests
=> Highlighting changes

CHANGELOG.md, package.json, src/example-types/results.js
Adding back the small refactoring
=> Results Highlights Refactoring

CHANGELOG.md, package.json, src/example-types/facet.js
Fix too many buckets being created by aggregation
=> [WIP]fix: update facet ordering term

CHANGELOG.md, package.json, src/example-types/bool.js, src/example-types/exists.js, test/example-types/bool.js, test/example-types/exists.js
- Changes the `hasValue` for bool/exists
- Adds tests
=> Change hasValue for bool/exists add tests

CHANGELOG.md, package.json, src/example-types/date.js
=> New rolling date ranges.

CHANGELOG.md, package.json, src/example-types/schemaMapping.js
Implemented support for scaled_float.
=> Implemented support for scaled_float.

CHANGELOG.md, README.md, src/example-types/dateHistogram.js
-[DateHistogram] no more extended bounds, it's lost to the abyss
=> Kill dead things

src/example-types/bool.js, src/example-types/cardinality.js, src/example-types/exists.js, src/example-types/facet.js, src/example-types/geo.js, src/example-types/groupedMetric.js, src/example-types/matchStats.js, src/example-types/number.js, src/example-types/numberRangeHistogram.js, src/example-types/numberUtil.js, src/example-types/percentiles.js, src/example-types/rangeStats.js, test/example-types/percentileRange.js, test/example-types/percentiles.js
=> just syntax crunching

CHANGELOG.md, package.json, src/dateUtil.js
fix npm version and
add next18Months rolling date type option
=> fix the npm version

CHANGELOG.md, package.json, src/example-types/filters/number.js, test/example-types/filters/number.js
=> [number] Fix bug with `findBestRange`

CHANGELOG.md, package.json, src/example-types/filters/number.js, test/integration/es7.js
* [number] Fix additional bug with `findBestRange` (map result keys to number)
=> Number bug fix

src/example-types/filters/tagsQuery.js
=> Proposed change

CHANGELOG.md, package.json, src/example-types/results.js, test/example-types/results.js
* [results] Respect `highlight: false` to opt out highlighting (regression from 1.0)
=> Respect `highlight: false`

CHANGELOG.md, package.json, src/example-types/filters/tagsQuery.js, test/example-types/filters/tagsQuery.js
- Replace all special chars with ` \\u0020` to prevent undesired search behavior
- Update tests
=> Replace special chars with empty space

CHANGELOG.md, package.json, src/example-types/filters/tagsQuery.js, test/example-types/filters/tagsQuery.js
- Cap `validContext` to `maxTagCount` of 100
=> Limit `tagsQuery` `validContext` to max of 100 tags

CHANGELOG.md, package-lock.json, package.json, src/example-types/filters/tagsQuery.js, src/example-types/filters/text.js, src/utils/fields.js, test/example-types/filters/text.js
Use prefix instead of regexp where we can
=> first take using prefix queries instead of regexps

CHANGELOG.md, package-lock.json, package.json, src/utils/dateUtil.js
=> feat: add last day/hour date math

CHANGELOG.md, package-lock.json, package.json, src/index.js, src/utils/redisCache.js
=> [feature] Redis Cache: storing searches in redis with smart refresh

CHANGELOG.md, package-lock.json, package.json, src/utils/regex.js, test/example-types/filters/facet.js, test/example-types/legacy/terms_stats.js, test/example-types/metricGroups/fieldValuesGroupStats.js, test/utils/regex.js
Fix issue with regex util to comply with https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#regexp-query-ex-request
=> Fix issue with regex util

CHANGELOG.md, package-lock.json, package.json, src/example-types/filters/text.js, test/example-types/filters/text.js
- `Must not` should be an `OR` vs `AND` currently
=> Fix the must not to `OR` vs `AND`

CHANGELOG.md, package-lock.json, package.json, src/index.js
* Use `debug` to see request query and response and timings.
* Add request to meta before sending the query so that Contexture dev tools can see the request without waiting for the response.
```
DEBUG=contexture:* DEBUG_DEPTH=100 npm start
```
=> Debug queries

CHANGELOG.md, package.json, src/example-types/schemaMapping.js
Add date to the schema mapping for elastic search
References https://github.com/smartprocure/spark/pull/11519
=> Add date field to schema mapping

.github/workflows/pull-request.yaml, CHANGELOG.md, package-lock.json, package.json
=> ci: update pull-request test failure case

CHANGELOG.md, package-lock.json, package.json, src/example-types/metricGroups/pivot.js
Not sure how this happened, but:
* Fix bug with pivot drilldown wrapping tree and processResponse not handling it
=> Pivot Drilldown Bugfix

CHANGELOG.md, package.json, src/example-types/metricGroups/pivot.js, test/example-types/metricGroups/pivot.js
=> Fix: pivot drilldown metrics and counts

CHANGELOG.md, package-lock.json, package.json, src/example-types/filters/tagsQuery.js, test/example-types/filters/tagsQuery.js, test/example-types/metricGroups/pivot.js, test/example-types/metricGroups/tagsQueryGroupStats.js
- Update level at which the children are spread
- Update tests
=> Fix: level at which child aggregations are spread on tags query filter

CHANGELOG.md, package-lock.json, package.json, src/example-types/metricGroups/pivot.js, test/example-types/metricGroups/pivot.js
[GS-2204](https://govspend.atlassian.net/browse/GS-2204)
=> [feature] Pivot pagination

.github/workflows/push-master.yaml
Skipping the version bump because the bug this fixes prevented the last one from getting published.
=> fixed the publish github action

test/example-types/metricGroups/pivot.test.js
=> Smaller test diff

CHANGELOG.md, package.json, src/example-types/metricGroups/pivot.js
=> fix(pivot): expansions initialization

CHANGELOG.md, package.json, src/example-types/metricGroups/dateRangesGroupStats.js, test/example-types/metricGroups/dateRangeGroupStats.test.js
☝️ 
1. Fix the drilldown to actually work with date-range joined drilldown value
2. Add unit tests.
=> fix: date ranges drilldown

CHANGELOG.md, package.json, src/example-types/metricGroups/dateRangesGroupStats.js, src/example-types/metricGroups/numberRangesGroupStats.js, src/example-types/metricGroups/pivot.js, test/example-types/metricGroups/dateRangesGroupStats.test.js, test/example-types/metricGroups/numberRangesGroupStats.test.js
Factor out `filterGroupRanges` to the corresponding group stats types and add/backfill tests.
=> refactor: filter group ranges
